version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: interview-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: market-handler